name: @ko-developerhong/react-native-crypto-rsa Package

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: building
        run: yarn prepare

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Initialize Git user
        run: |
          git config --global user.email "dea972@naver.com"
          git config --global user.name "ko-devHong"

      - name: Run release
        run: |
          echo "GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}"
          npm config set @ko-developerhong:registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          yarn release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
